DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER(
  ID INTEGER Primary key,
  BONUS INTEGER,
  FIRST_NAME varchar(30) not null,
  LAST_NAME varchar(30) not null);

DROP TABLE IF EXISTS MOVIES;

CREATE TABLE MOVIES(
  ID INTEGER Primary key,
  MOVIETYPEID INTEGER,
  TITLE varchar(30) not null,
  DESCRIPTION varchar(200) not null);

DROP TABLE IF EXISTS MOVIETYPES;

CREATE TABLE MOVIETYPES(
ID INTEGER Primary key,
DESCRIPTION varchar(200) not null);

DROP TABLE IF EXISTS TRANSACTIONS;

CREATE TABLE TRANSACTIONS(
  ID INTEGER Primary key,
  CUSTOMER_ID INTEGER,
  MOVIE_ID INTEGER,
  N_DAYS INTEGER,
  N_EXTRA_DAYS INTEGER,
  PRICE INTEGER,
  IS_SETTLED INTEGER);

